<?php
return [
    'crawl',
    'bot',
    'crawler',
    'google',
    'bing',
    'yahoo',
    'Java',
	'FreeBSD',
	'msnbot',
	'Yahoo! Slurp',
	'YahooSeeker',
	'Googlebot',
	'bingbot',
	'crawler', 
	'PycURL',
    'datapacket',
    'yisouspider',
    'Clickagy',
    'Clickagy Intelligence Bot v2',
	'facebookexternalhit',
    'AhrefsBot',
    'AhrefsSiteAudit',
    'vpn',
    'Alexa Crawler',
    'Archive.org_bot',
    'AspiegelBot',
    'Baiduspider',
    'Bingbot',
    'Botify',
    'Botscraper',
    'Catchpoint',
    'Cognitiveseo',
    'Common Crawl',
    'DeepCrawl',
    'Diffbot',
    'DotBot',
    'DotBot',
    'DuckDuckBot',
    'Exabot',
    'Findxbot',
    'Gigablast',
    'Giraffebot',
    'Googlebot',
    'LinkdexBot',
    'Lipperhey',
    'Majestic-12 Bot',
    'MojeekBot',
    'MozBot',
    'NetEstate NE Crawler',
    'OnCrawl',
    'OpenWebSpider',
    'OrangeBot',
    'PetalBot',
    'PiplBot',
    'Qwantify',
    'RyteBot',
    'Screaming Frog SEO Spider',
    'Scrubby',
    'SearchmetricsBot',
    'SEMrushBot',
    'SEOENGBot',
    'SEOkicks-Robot',
    'SEOkicks',
    'SEOlyzer',
    'SerendeputyBot',
    'SerpstatBot',
    'SeznamBot',
    'SeznamBot',
    'SISTRIX Crawler',
    'Sitebulb Crawler',
    'Slurp Bot',
    'Sogou Spider',
    'SpyFuBot',
    'StormCrawler',
    'TinEye',
    'Ubersuggest Bot',
    'Veoozbot',
    'WebMeUp',
    'WorldWideWeb Worm',
    'XoviBot',
    'YacyBot',
    'Yandex Bot',
    'ZoomInfoBot',
];
?>